sudo: false
lanugage: generic
matrix:
  include:
  - os: linux
cache:
  directories:
  - "/tmp/texlive"
  - "$HOME/.texlive"
before_install:
- bash ./utilities/travis_setup.sh
- export PATH="/tmp/texlive/bin/x86_64-linux:$PATH"
script:
- latexmk -pdf -interaction=nonstopmode -halt-on-error abstract.tex
after_success:
- bash ./utilities/deploy.sh
deploy:
  provider: releases
  api_key:
    secure: qySzW/oB8V89TFFdjSdmLSeErGTulMbY2M8Cl6WSLMpsRKfEarMUfFmU32pelhjJIABp3IuCs9SFJsz5HX5cJdcDCh9jOIybqa09SCdivxy6UIXGBgtht4xJ6l/6m57jASdG4iDlmLnSLVMYZVgwaS3Xo8/vwb31VCb9hJ8skv3vjkPxLafl134DhqiN7Tjqh9Vb3sL2oDnn1c6foV7ig458e5o3lDdD+nG6IFSrqL/4p8pZYilEaztJCqYVWXvAXgXdrS1ywHS9XPK0g2zrMJ6emSmil00Vf+2+cah0eQo/XdCW6Lx/gApk4AW+1jhi9h5EnersH5msxELLtfqws9BPE+s7yVI4cZQ7Zz/oqqHf16g36dsoCm3IJAeZF7/Rmdfn7gcv59uwEKOCT4/BiQehNBHWVnv09PyML4hXirSE5RGVNuIP2w5DgoKYf0gbbk43Xl9miyDg5qyODPRIb5BMJRWZLoNC6wc2QgJn66X0kwKGV/E7hh6xVr3It1kYeV27xQq3q0L5+ILCpLeuEmq2sa0YIH8YhPJnBR+7oLhaNN3MBGA2C+fBzTKyDgBhgVataOlM9V4aEcQl+VH1Yce/MnWoRvMp3OQbhQXRx71xDcAcYsUtCan0JqqRwGVqCCI4uSVismOFJdlC5frxRWcPhJpsdGH+XcRs/wwytIE=
  file: abstract.pdf
  skip_cleanup: true
  on:
    repo: skulumani/2018_RD_abstract
